# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CamLandEc-RM03
logo: ""
email: ""
description: >- # this means to ignore newlines until "baseurl:"
  Course material for RM03 in lent term, 2020
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: haifengniu
github_username:  hn303
permalink: :title

repository: "hn303.github.io/CamLandEc-RM03"

theme: jekyll-theme-cayman

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# A list of the pages to display in the navigation bar
header_pages:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:


show_excerpts: true

show_downloads: false
google_analytics: ""
google_analytics_anonymize: false
darkmode: false
hide_first_title: false # Useful if README.md is used on both github and pages
logo_url: ./logo.png # Either absolute or relative url
syntax_theme: ./syntax.css # Leave empty for default, otherwise link to a pygments stylesheet
colors:
    gradient_left: "#155799"
    gradient_right: "#159957"
    header: "#fff"
    android_theme: "#000" # this default to gradient_color
    link: "#1e6bb8" # this default to gradient_color
    section_title: "#155799" # this default to gradient_color
buttons:
      zip_url: http://example.com/
      zip_title: Title
      zip_hide: true
      tar_url: http://example.com/
      tar_title: Title
      tar_hide: true
      github_hide: true # hides "View on Github"
